---
#
# OS Packages
#
# Packages to install via the OS package manager (apt-get).
#
os::packages:
  memcached: true
  mongodb: true
  pv: true
  php-apc: true
  php5-gd: true
  php5-mcrypt: true
  php5-memcached: true
  php5-mongo: true
  php5-mssql: true
  libsybdb5: true
  libmemcached-dev: true
  vim: true

#
# PHP Builds
#
# A hash containing a list of PHP versions and their configurations
#  to be managed by phpbrew.
#

# enable mssql
#sudo ln -s /usr/lib/x86_64-linux-gnu/libsybdb.so.5.0.0 /usr/lib/libsybdb.so
#sudo ldconfig -v

php::builds:
  5.4.40:
    installed: true
    default: true
    variants:
      - dev
      - dbs
      - gd
      - mcrypt
      - --with-mssql
    extensions:
      apc:
        enabled: true
        version: stable
      gd:
        enabled: true
        version: stable
      http:
        enabled: true
        version: 1.7.6
      memcached:
        enabled: true
        version: stable
      mongo:
        enabled: true
        version: stable
      mssql:
        enabled: true
        version: stable
      redis:
        enabled: true
        version: stable
      xdebug:
        enabled: true
        version: stable
      xhprof:
        enabled: true
        version: latest
    fpm:
      port: 9002
      autostart: true

#
# Apache Modules
#
# Apache modules to install and enable.
#
apache::modules:
  rewrite: true

#
# Nodejs Modules
#
# Nodejs Modules to install via npm.
#
npm::packages:
  grunt-cli: true

#
# Debug mode
#
# Enables extra information during provisioning
#
debug: false
